### ISSUE TITLE
Cannot run the basic code

### ISSUE THREAD

**Issue by jtong99** [DocYard-ai/UCR#5]
I installed the UCR on Google Colab. But I cannot run it.

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-15-334d5783a886> in <module>()
      1 from ucr import UCR
----> 2 ocr = UCR(l='ko', device='gpu') # use l or lang='language_id'.
      3 
      4 # Run Predictions
      5 result = ocr.predict('input_path', o='output_path')

2 frames
/usr/local/lib/python3.7/dist-packages/ucr/ucr.py in __init__(self, **kwargs)
    394         config["Classification"] = config_cls
    395 
--> 396         super().__init__(config)
    397 
    398     def predict(

/usr/local/lib/python3.7/dist-packages/ucr/inference/infer_system.py in __init__(self, config)
     46 class TextSystem(object):
     47     def __init__(self, config):
---> 48         self.text_detector = infer_det.TextDetector(config["Detection"])
     49         self.text_recognizer = infer_rec.TextRecognizer(config["Recognition"])
     50         self.text_classifier = infer_cls.TextClassifier(

/usr/local/lib/python3.7/dist-packages/ucr/inference/infer_det.py in __init__(self, config)
     46     def __init__(self, config):
     47         self.device = config["device"]
---> 48         print(self.device)
     49         self.det_algorithm = config["Architecture"]["algorithm"]
     50         self.preprocess_op = build_preprocess(config["Preprocess"])

KeyError: 'Architecture'
```

![Screenshot from 2021-11-05 15-55-18](https://user-images.githubusercontent.com/45779362/140484362-11f9a1b0-f18f-4640-98d0-8807fdec6dd8.png)

**Comment by christian-becker-ta** [comment]
Same for me

**Comment by christian-becker-ta** [comment]
Found the issue. 
The provided config file has probably changed, and so the keys are not anymore right. This can be adjusted on your own, by adding on each error the same word in lower case. 
f.e config["Architecture"]["algorithm"] has to be changed to config["architecture"]["Architecture"]["algorithm"]

Same for "Preprocess" and "Postprocess". Then everything runs properly, and also the results are quite good. 

`{
   "preprocess":{
      "Preprocess":[
         {
            "DetResizeForTest":{
               "resize_long":1920
            }
         },
         {
            "NormalizeImage":{
               "scale":"1./255.",
               "mean":[
                  0.485,
                  0.456,
                  0.406
               ],
               "std":[
                  0.229,
                  0.224,
                  0.225
               ],
               "order":"hwc"
            }
         },
         {
            "ToCHWImage":"None"
         },
         {
            "KeepKeys":{
               "keep_keys":[
                  "image",
                  "shape"
               ]
            }
         }
      ]
   },
   "architecture":{
      "Architecture":{
         "model_type":"det",
         "algorithm":"CRAFT",
         "Transform":"None",
         "Backbone":{
            "name":"VGG16_BN"
         },
         "Neck":{
            "name":"CRAFTFPN"
         },
         "Head":{
            "name":"CRAFTHead"
         }
      }
   },
   "postprocess":{
      "Postprocess":{
         "name":"CRAFTPostProcess",
         "text_thresh":0.35,
         "link_thresh":0.1,
         "min_size":3,
         "use_dilate":false,
         "xdilate":9,
         "ydilate":3,
         "xpad":4,
         "ypad":4,
         "rotated_box":true
      }
   },
   "job_name":"det_infer",
   "level":"INFO",
   "batch_size":1,
   "device":"cpu",
   "input":"test/",
   "output":"test_output/",
   "model_location":"C:\\Users\\cbec/.ucr/1.0/det\\det_vgg_craft\\model.pt"
}`

**Comment by jtong99** [comment]
Appreciated!

**Comment by sizhky** [comment]
Isn't there a permanent fix for this?
